services:

    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Tool\TokenGeneratorInterface: '@MembersBundle\Tool\TokenGenerator'
    MembersBundle\Tool\TokenGenerator: ~

    MembersBundle\Tool\ClassInstaller: ~
