services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # validator constraints
    MembersBundle\Validator\Constraints\PimcoreUniqueEntity: ~

    # validator constraints
    MembersBundle\Validator\Constraints\PimcoreUniqueEntityValidator:
        tags:
            - { name: validator.constraint_validator, alias: members.validator.unique }