# frontend password change
members_user_change_password:
    path: /change-password
    defaults: { _controller: MembersBundle\Controller\ChangePasswordController::changePasswordAction }
    methods:  [GET, POST]