services:
    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Controller\OAuthController:
        public: true
        arguments:
            $formFactory: '@members.oauth.complete_profile.form.factory'
        tags: ['controller.service_arguments']