services:
    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Manager\SsoIdentityManagerInterface: '@MembersBundle\Manager\SsoIdentityManager'
    MembersBundle\Manager\SsoIdentityManager: ~
