services:
    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Security\OAuth\AccountConnectorInterface: '@MembersBundle\Security\OAuth\AccountConnector'
    MembersBundle\Security\OAuth\AccountConnector: ~

    MembersBundle\Security\OAuthIdentityAuthenticator: ~

    MembersBundle\Security\OAuth\Dispatcher\ConnectDispatcher: ~
    MembersBundle\Security\OAuth\Dispatcher\LoginDispatcher: ~

    MembersBundle\Security\OAuth\OAuthRegistrationHandler: ~

