services:
    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Service\ResourceMappingService:
        arguments:
            $authIdentifier: '%members.auth.identifier%'

    MembersBundle\Service\SsoIdentityStatusServiceInterface: '@MembersBundle\Service\SsoIdentityStatusService'
    MembersBundle\Service\SsoIdentityStatusService: ~

