services:
    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Service\ResourceMappingService: ~

    MembersBundle\Service\SsoIdentityStatusServiceInterface: '@MembersBundle\Service\SsoIdentityStatusService'
    MembersBundle\Service\SsoIdentityStatusService: ~

