services:
    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Security\OAuth\OAuthTokenStorageInterface: '@MembersBundle\Security\OAuth\OAuthTokenStorage'
    MembersBundle\Security\OAuth\OAuthTokenStorage: ~
