#!/usr/bin/env bash

export DACHCOM_BUNDLE_HOME=$TRAVIS_BUILD_DIR
export DACHCOM_BUNDLE_NAME="Members"
export DACHCOM_BUNDLE_REPO_NAME="members"
export DACHCOM_BUNDLE_COMMIT=$TRAVIS_COMMIT
export DACHCOM_BUNDLE_BRANCH=$TRAVIS_BRANCH

export DACHCOM_BUNDLE_CLASS='MembersBundle\MembersBundle'
export DACHCOM_BUNDLE_INSTALLER_CLASS='MembersBundle\Tool\Install'

declare -A DACHCOM_INSTALL_CONFIG_FILES=(
 # system files
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/extensions.php.template"]="var/config/extensions.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/debug.php.template"]="var/config/debug-mode.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/system.yml.template"]="var/config/system.yml"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/appKernel.php.template"]="app/AppKernel.php"
 # template files
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/controller/DefaultController"]="src/AppBundle/Controller/DefaultController.php"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/views/default"]="app/Resources/views/Default/default.html.twig"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/views/snippet"]="app/Resources/views/Default/snippet.html.twig"
 ["$DACHCOM_BUNDLE_HOME/_etc/config/bundle/template/views/staticRoute"]="app/Resources/views/Default/staticRoute.html.twig"
)