# frontend routing
members_oauth:
    resource: '@MembersBundle/Resources/config/pimcore/routing/oauth.yml'
    prefix: /

members_auth:
    resource: '@MembersBundle/Resources/config/pimcore/routing/auth.yml'
    prefix: /{_locale}/members

members_registration:
    resource: '@MembersBundle/Resources/config/pimcore/routing/registration.yml'
    prefix: /{_locale}/members/register

members_change_password:
    resource: '@MembersBundle/Resources/config/pimcore/routing/change_password.yml'
    prefix: /{_locale}/members/profile

members_profile:
    resource: '@MembersBundle/Resources/config/pimcore/routing/profile.yml'
    prefix: /{_locale}/members/profile

members_resetting:
    resource: '@MembersBundle/Resources/config/pimcore/routing/resetting.yml'
    prefix: /{_locale}/members/resetting

members_delete_account:
    resource: '@MembersBundle/Resources/config/pimcore/routing/delete_account.yml'
    prefix: /{_locale}/members/profile
