security:
    password_hashers:
        'Pimcore\Model\DataObject\MembersUser': 'members.security.pimcore_password_hasher'
        'MembersBundle\Adapter\User\UserInterface': 'members.security.pimcore_password_hasher'

services:
    members.security.pimcore_password_hasher:
        class: MembersBundle\Security\PimcorePasswordHasher
