<?php

namespace MembersBundle\DependencyInjection;

use MembersBundle\Form\Type\ChangePasswordFormType;
use MembersBundle\Form\Type\DeleteAccountFormType;
use MembersBundle\Form\Type\ProfileFormType;
use MembersBundle\Form\Type\RegistrationFormType;
use MembersBundle\Form\Type\LoginFormType;
use MembersBundle\Form\Type\ResettingFormType;
use MembersBundle\Form\Type\ResettingRequestFormType;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('members');
        $rootNode
            ->children()
                ->booleanNode('send_admin_mail_after_register')->end()
                ->booleanNode('send_user_mail_after_confirmed')->end()
                ->scalarNode('post_register_type')->end()
                ->scalarNode('storage_path')->cannotBeEmpty()->defaultValue('/members')->end()
                ->arrayNode('user')
                    ->addDefaultsIfNotSet()
                    ->isRequired()
                    ->children()
                        ->arrayNode('adapter')
                            ->children()
                                ->scalarNode('class_name')->end()
                            ->end()
                        ->end()
                        ->arrayNode('initial_groups')
                            ->prototype('scalar')->end()
                            ->validate()
                                ->ifEmpty()
                                ->thenEmptyArray()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('group')
                    ->isRequired()
                    ->children()
                        ->arrayNode('adapter')
                            ->children()
                                ->scalarNode('class_name')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('auth')
                    ->isRequired()
                        ->children()
                        ->arrayNode('adapter')
                            ->children()
                                ->scalarNode('class_name')->end()
                                ->scalarNode('object_path')->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('restriction')
                    ->isRequired()
                    ->children()
                        ->booleanNode('enabled')->defaultFalse()->end()
                        ->arrayNode('allowed_objects')
                            ->prototype('scalar')->end()
                            ->validate()
                                ->ifEmpty()
                                ->thenEmptyArray()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('relations')
                    ->addDefaultsIfNotSet()
                    ->children()

                        ->arrayNode('login')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                            ->children()
                                ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('type')->defaultValue(LoginFormType::class)->end()
                                        ->scalarNode('name')->defaultValue('members_user_login_form')->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(['Login', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()

                        ->arrayNode('profile')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                            ->children()
                                ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('type')->defaultValue(ProfileFormType::class)->end()
                                        ->scalarNode('name')->defaultValue('members_user_profile_form')->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(['Profile', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()

                        ->arrayNode('change_password')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                                ->children()
                                    ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('type')->defaultValue(ChangePasswordFormType::class)->end()
                                        ->scalarNode('name')->defaultValue('members_user_change_password_form')->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(['ChangePassword', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()

                        ->arrayNode('registration')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                                ->children()
                                    ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                        ->children()
                                            ->scalarNode('type')->defaultValue(RegistrationFormType::class)->end()
                                            ->scalarNode('name')->defaultValue('members_user_registration_form')->end()
                                            ->arrayNode('validation_groups')
                                                ->prototype('scalar')->end()
                                                ->defaultValue(['Registration', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()

                        ->arrayNode('resetting_request')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                                ->children()
                                    ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                        ->children()
                                        ->scalarNode('type')->defaultValue(ResettingRequestFormType::class)->end()
                                        ->scalarNode('name')->defaultValue('members_user_resetting_request_form')->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(['ResetPassword', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()

                        ->arrayNode('resetting')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                                ->children()
                                    ->scalarNode('retry_ttl')->defaultValue(7200)->end()
                                    ->scalarNode('token_ttl')->defaultValue(86400)->end()
                                    ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                        ->children()
                                        ->scalarNode('type')->defaultValue(ResettingFormType::class)->end()
                                        ->scalarNode('name')->defaultValue('members_user_resetting_form')->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(['ResetPassword', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
						->end()

                        ->arrayNode('delete_account')
                            ->addDefaultsIfNotSet()
                            ->canBeUnset()
                                ->children()
                                    ->arrayNode('form')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('type')->defaultValue(DeleteAccountFormType::class)->end()
                                        ->scalarNode('name')->defaultValue('members_user_delete_account_form')->end()
                                        ->arrayNode('validation_groups')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(['DeleteAccount', 'Default'])
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('emails')
                    ->isRequired()
                        ->children()
                        ->arrayNode('default')
                            ->children()
                                ->scalarNode('register_confirm')->isRequired()->cannotBeEmpty()->end()
                                ->scalarNode('register_confirmed')->isRequired()->cannotBeEmpty()->end()
                                ->scalarNode('register_password_resetting')->isRequired()->cannotBeEmpty()->end()
                                ->scalarNode('admin_register_notification')->isRequired()->cannotBeEmpty()->end()
                            ->end()
                        ->end()
                        ->arrayNode('sites')
                            ->prototype('array')
                            ->children()
                                ->scalarNode('main_domain')
                                    ->isRequired()
                                    ->cannotBeEmpty()
                                ->end()
                                ->arrayNode('emails')
                                    ->children()
                                        ->scalarNode('register_confirm')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('register_confirmed')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('register_password_resetting')->isRequired()->cannotBeEmpty()->end()
                                        ->scalarNode('admin_register_notification')->isRequired()->cannotBeEmpty()->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end()
        ;

        return $treeBuilder;
    }
}