MembersBundle\Adapter\User\UserInterface:
    constraints:
        -  MembersBundle\Validator\Constraints\PimcoreUniqueEntity:
            fields: [userName]
            message: members.validation.username.already_used
            groups: [Registration, UsernameOnlyRegistration, Profile, CompleteProfile, SSO]
        -  MembersBundle\Validator\Constraints\PimcoreUniqueEntity:
            fields: [email]
            message: members.validation.email.already_used
            groups: [Registration, EmailOnlyRegistration, Profile, CompleteProfile, SSO]
    getters:
        userName:
            - NotBlank: { message: members.validation.username.blank, groups: [Registration, UsernameOnlyRegistration, Profile, CompleteProfile, SSO, SSOUsernameOnly] }
            - Length: { min: 3, max: 180, minMessage: members.validation.username.short, maxMessage: members.validation.username.long, groups: [Registration, UsernameOnlyRegistration, Profile, CompleteProfile, SSO] }
        email:
            - NotBlank: { message: members.validation.email.blank, groups: [Registration, EmailOnlyRegistration, Profile, CompleteProfile, SSO, SSOEmailOnly] }
            - Length: { min: 3, max: 180, minMessage: members.validation.email.short, maxMessage: members.validation.email.long, groups: [Registration, EmailOnlyRegistration, Profile, CompleteProfile, SSO] }
            - Email: { message: members.validation.email.invalid }
        plainPassword:
            - NotBlank: { message: members.validation.password.blank, groups: [Registration, UsernameOnlyRegistration, EmailOnlyRegistration, CompleteProfile, ResetPassword, ChangePassword] }
            - Length: { min: 5, max: 4096, minMessage: members.validation.password.short, groups: [Registration, UsernameOnlyRegistration, EmailOnlyRegistration, Profile, CompleteProfile, ResetPassword, ChangePassword] }