services:

    members.change_password.form.factory:
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - '%members_user.change_password.form.name%'
            - '%members_user.change_password.form.type%'
            - '%members_user.change_password.form.validation_groups%'

    MembersBundle\Form\Type\ChangePasswordFormType:
        arguments:
            - '\MembersBundle\Adapter\User\UserInterface'
        tags:
            - { name: form.type, alias: members_user_change_password }

    MembersBundle\Controller\ChangePasswordController:
        public: true
        autowire: true
        autoconfigure: true
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            $formFactory: '@members.change_password.form.factory'
