services:

    MembersBundle\Command\ClassInstallerCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $classInstaller: '@MembersBundle\Tool\ClassInstaller'
        tags:
            - {name: console.command, command: 'members:install:class' }

    MembersBundle\Command\OAuthSetupCommand:
        autowire: true
        autoconfigure: true
        arguments:
            $oauthEnabled: '%members.oauth.enabled%'
            $classInstaller: '@MembersBundle\Tool\ClassInstaller'
            $classManager: '@MembersBundle\Manager\ClassManagerInterface'
        tags:
            - {name: console.command, command: 'members:oauth:setup' }
