services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MembersBundle\Mailer\Mailer: ~
    MembersBundle\Mailer\MailerInterface: '@MembersBundle\Mailer\Mailer'