services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MembersBundle\Mailer\MailerInterface: '@MembersBundle\Mailer\Mailer'
    MembersBundle\Mailer\Mailer: ~

    MembersBundle\Controller\EmailController:
        public: true
        autowire: true
        autoconfigure: true