services:

    _defaults:
        autowire: true
        autoconfigure: true

    MembersBundle\Mailer\MailerInterface: '@MembersBundle\Mailer\Mailer'
    MembersBundle\Mailer\Mailer: ~

    MembersBundle\Controller\EmailController:
        public: true
        autowire: true
        autoconfigure: true
        calls:
            - [setContainer, ['@service_container']]