services:

    members.registration.form.factory:
        class: MembersBundle\Form\Factory\FormFactory
        arguments:
            - '@form.factory'
            - '%members_user.registration.form.name%'
            - '%members_user.registration.form.type%'
            - '%members_user.registration.form.validation_groups%'

    MembersBundle\Form\Type\RegistrationFormType:
        arguments:
            - '\MembersBundle\Adapter\User\UserInterface'
        tags:
            - { name: form.type, alias: members_user_registration }

    MembersBundle\Controller\RegistrationController:
        public: true
        autowire: true
        autoconfigure: true
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            $formFactory: '@members.registration.form.factory'
