services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MembersBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('MembersBundle')"
        calls:
            - [setTokenStorageUserResolver, ['@Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver']]
            - [setSerializer, ['@serializer']]
            - [setConfiguration, ['@MembersBundle\Configuration\Configuration']]