services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # tool: installer
    MembersBundle\Tool\Install:
        arguments:
            $bundle: "@=service('kernel').getBundle('MembersBundle')"
        calls:
            - [setTokenStorageUserResolver, ['@Pimcore\Bundle\AdminBundle\Security\User\TokenStorageUserResolver']]
            - [setSerializer, ['@serializer']]
            - [setConfiguration, ['@MembersBundle\Configuration\Configuration']]

    # tool: installer
    MembersBundle\Tool\TokenGenerator: ~

    # configuration
    MembersBundle\Configuration\Configuration: ~

    # session: configurator
    MembersBundle\Session\SessionConfigurator:
        tags:
            - { name: pimcore.session.configurator }