members.controller.admin.get_restriction_config:
    path: /admin/members/restriction/get-document-restriction-config
    defaults: { _controller: MembersBundle\Controller\Admin\RestrictionController::getDocumentRestrictionConfigAction }
members.controller.admin.set_document_restriction:
    path: /admin/members/restriction/set-document-restriction-config
    defaults: { _controller: MembersBundle\Controller\Admin\RestrictionController::setDocumentRestrictionConfigAction }
members.controller.admin.get_global_settings:
    path: /admin/members/restriction/get-global-settings
    defaults: { _controller: MembersBundle\Controller\Admin\RestrictionController::getGlobalSettingsAction }
members.controller.admin.get_groups:
    path: /admin/members/restriction/get-groups
    defaults: { _controller: MembersBundle\Controller\Admin\RestrictionController::getGroupsAction }
members.controller.admin.get_next_parent_restriction:
    path: /admin/members/restriction/get-next-parent-restriction
    defaults: { _controller: MembersBundle\Controller\Admin\RestrictionController::getNextParentRestrictionAction }
members.asset_request:
    path: /members/request-data/{hash}
    defaults: { _controller: MembersBundle\Controller\RequestController::serveAction }
members.asset_path_request:
    path: /members/asset/{id}/{path}.{extension}
    defaults: { _controller: MembersBundle\Controller\RequestController::serveProtectedAssetPathAction }